@baseUrl = http://localhost:3333

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Amaury Euzebio",
  "email": "amaury@a1tecnologia.info",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "amaury@a1tecnologia.info",
  "password": "123456"
}